package com.example.demo.domain.simple.repository;

import com.example.demo.domain.entity.Item;
import com.example.demo.domain.entity.ItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ItemRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbg.generated Thu Mar 24 02:05:29 JST 2022
     */
    long countByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbg.generated Thu Mar 24 02:05:29 JST 2022
     */
    int deleteByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbg.generated Thu Mar 24 02:05:29 JST 2022
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbg.generated Thu Mar 24 02:05:29 JST 2022
     */
    int insert(Item row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbg.generated Thu Mar 24 02:05:29 JST 2022
     */
    int insertSelective(Item row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbg.generated Thu Mar 24 02:05:29 JST 2022
     */
    List<Item> selectByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbg.generated Thu Mar 24 02:05:29 JST 2022
     */
    Item selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbg.generated Thu Mar 24 02:05:29 JST 2022
     */
    int updateByExampleSelective(@Param("row") Item row, @Param("example") ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbg.generated Thu Mar 24 02:05:29 JST 2022
     */
    int updateByExample(@Param("row") Item row, @Param("example") ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbg.generated Thu Mar 24 02:05:29 JST 2022
     */
    int updateByPrimaryKeySelective(Item row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbg.generated Thu Mar 24 02:05:29 JST 2022
     */
    int updateByPrimaryKey(Item row);
}