
spring.profiles:
  group:
    local:
      - dev
      - h2
      - common
    prod:
      - postgres
      - common
    common:
      - domain
      - hoge
      - oauth2login
  default: local


##
services.auth:
  base-url: http://localhost:8080/auth

##
spring.session:
  store-type: none
