## アプリケーション設定
spring.application:
  name: demo-web
    
## プロファイル設定
spring.profiles:
  group:
    local:
      - dev
      - h2
      - common
    prod:
      - postgres
      - common
    common:
      - domain
      - hoge
      - oauth2client
      #- oauth2client-public
      - oauth2client-demoapp
  default: local

## ログレベル設定
logging.level:
  '[com.example.demo]': debug
  '[org.springframework.security]': info

## ログファイル設定
logging:
  file:
    path: target
    name: ${logging.file.path}/hoge.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      file-name-pattern: ${logging.file.path}/hoge-%d{yyyy-MM-dd}.%i.log
      max-history: 7
      max-file-size: 10KB

## メッセージ設定
spring.messages:
  basename: messages.messages
  cache-duration: -1

## Spring Session
spring.session:
  store-type: none

## Tomcat
server.tomcat:
  basedir: target/tomcat.${server.port:8080}

server.servlet:
  context-path: /demo

## エラーページ設定
server.error:
  path: /error
  include-binding-errors: always
  include-exception: true
  include-message: always
  include-stacktrace: never
  whitelabel.enabled: false

## 認証
common.auth:
  enabled: true
  failure-url: ${server.error.path}
  #successUrl: /hello2
  use-dummy-user: true
  oauth2-login:
    enabled: true
    base-uri: http://localhost:18080/auth/realms/demo
    logout-uri: ${common.auth.oauth2-login.base-uri}/protocol/openid-connect/logout
    #client-id: publicapp
    #client-secret:
    client-id: demoapp
    client-secret: 08c33835-c18c-4dd7-a7df-aee3479d17c4
  form-login: 
    enabled: false
    login-page: /login2

## データベース
common.datasource:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: postgres
